### ISSUE TITLE
hugginface demo

### ISSUE THREAD

**Issue by davidperez808006** [alibaba/Tora#11]
please add huggingface demo for people out of china

**Comment by Leojc** [comment]
We are applying for free GPU resource from HuggingFace at the moment. You can try out our English demo: <a href='https://www.modelscope.cn/studios/Alibaba_Research_Intelligence_Computing/Tora_En'><img src='https://img.shields.io/badge/🤖_ModelScope-EN_demo-%23654dfc'></a>
