### ISSUE TITLE
training data example

### ISSUE THREAD

**Issue by g-jing** [alibaba/Tora#14]
I understanding it is hard to release the full training data. Is it possible to release a training sample so we can follow it on customized data? Thanks!

**Comment by zhenghao977** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhenghao977** [comment]
Hello, since the trajectories are extracted using the optical flow model during training, you only need to prepare the videos and text captions following the CogVideo5B format. We will release some examples as soon as possible.

**Comment by Fancy93** [comment]
Very interesting idea， why use the optical flow model for extracting trajectories?
