### ISSUE TITLE
training speed

### ISSUE THREAD

**Issue by lijain** [alibaba/Tora#15]
Hi, see your work is based on the CogVideoX-5B model, because I trained this model before on A100 80g 16 pieces of hardware, batchsize=4 image size 384x640 training speed is an iter 26s. How many s per iter do you have? Is there a better way to optimize?

**Comment by Leojc** [comment]
Yes it's quite slow to train. Our speed is similar to yours. It seems there is no other way to optimize than DeepSpeed, which was already utilized.
