### ISSUE TITLE
"Does this model support CPU offloading for execution?"

### ISSUE THREAD

**Issue by SAT431** [alibaba/Tora#2]

**Comment by Leojc** [comment]
Not yet, since we implemented our trajectory module based on the sat model of CogVideoX, instead of the diffusers one. The GPU MEM requirement for inference now is 30GB.

**Comment by SAT431** [comment]
are you planning to implant cup_offloading in future

**Comment by SAT431** [comment]
Are you planning to implement CPU offloading in the future?

**Comment by Leojc** [comment]
Sure, but at the moment this isn't our top priority.
