### ISSUE TITLE
hi ,i have a problem about excuting app.py

### ISSUE THREAD

**Issue by zzddwyff** [alibaba/Tora#7]
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/autodl-tmp/Tora/sat/ckpts/t5-v1_1-xxl.

i don't know what I have misssed?????help help

**Comment by zhenghao977** [comment]
Please check the contents in the "t5-v1_1-xxl" directory. You can refer to the contents and structure in our [ModelScope weights ](https://www.modelscope.cn/models/xiaoche/Tora/files) for guidance.

**Comment by zzddwyff** [comment]
I already tried, I have download all files in your ModelScope weights/t5-v1_1-xxl,  there is no flie named "pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack" in your ModelScope weights/t5-v1_1-xxl ,   is that normal?

**Comment by Leojc** [comment]
> there is no flie named "pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack" in your ModelScope weights/t5-v1_1-xxl , is that normal?

Yes, that is normal. "model.safetensors" in the message refers to the "model-0000x-of-00002.safetensors" files. 
Maybe check if your working directory is the "sat" file, i.e. "cd sat" before runing. Because we use relative path here.
